//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppFLOyBUS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Planta
    {
        public Planta()
        {
            this.Pedido = new HashSet<Pedido>();
        }
    
        public int Id { get; set; }
        public string nombrePlanta { get; set; }
        public int valor { get; set; }
    
        public virtual ICollection<Pedido> Pedido { get; set; }
    }
}
